version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-research-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stock-research-network

  frontend:
    build:
      context: ./frontend/stock-research-ui
      dockerfile: Dockerfile
    container_name: stock-research-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stock-research-network

networks:
  stock-research-network:
    driver: bridge

volumes:
  logs:

